import {
  DashboardOutlined,
  UserAddOutlined,
  BorderOuterOutlined,
  HomeOutlined,
  LogoutOutlined,
} from "@ant-design/icons";
import React from "react";

export const dataSideBar = [
  {
    key: "1",
    label: "Dashboard",
    icon: React.createElement(DashboardOutlined),
    path: "/",
  },
  {
    key: "2",
    label: "Manage Users",
    icon: React.createElement(BorderOuterOutlined),
    path: "/admin/user",
  },
  {
    key: "3",
    label: "Add SubAdmin",
    icon: React.createElement(UserAddOutlined),
    path: "/admin/add-subadmin",
  },
  {
    key: "4",
    label: "Manage Company",
    icon: React.createElement(HomeOutlined),
    path: "/",
  },
  {
    key: "5",
    label: "Log out",
    icon: React.createElement(LogoutOutlined),
    path: "/login",
  },
];

export interface DataType {
  id: number;
  username: string;
  email: string;
  activated: boolean;
  role: string;
}

export const data: DataType[] = [
  {
    id: 1,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "CANDIDATE",
  },
  {
    id: 2,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 3,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 4,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 5,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 6,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 7,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 8,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 9,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 10,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 11,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 12,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 13,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 14,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 15,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 16,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 17,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 18,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 19,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 20,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 21,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 22,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 23,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 24,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 25,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 26,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 27,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 28,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 29,
    username: "thanhdien",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 30,
    username: "thanhdien",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 31,
    username: "thanhdien",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "ADMIN",
  },
  {
    id: 32,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "CANDIDATE",
  },
  {
    id: 33,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "CANDIDATE",
  },
  {
    id: 34,
    username: "John Brown",
    email: "thanhdien@gmail.com",
    activated: true,
    role: "CANDIDATE",
  },
];
